name: ci

on:
  push:
    tags:
      - 'v*.*.*'
  # schedule 2 weekly on Sunday at 4:05 AM UTC
  schedule:
    - cron: '5 4 * * 0'
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  AUTHOR: ${{ github.actor }}
  REPO_NAME: "traefik-forward-auth"
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  ci:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
#      - name: Show GitHub context   
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#        shell: bash
#      - name: TruffleHog OSS
#        uses: trufflesecurity/trufflehog@v3.29.1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/githubcdr/hosting-tools
            docker.io/cdrocker/hosting-tools
            git.codar.nl/codarhq/hosting-tools
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            maintainer=${{env.AUTHOR}}
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.url=https://codar.nl
            org.opencontainers.image.licenses=MIT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR Container registry
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
      - name: Login to Docker Container registry
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Codar Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CODARREPO_USERNAME }}
          password: ${{ secrets.CODARREPO_TOKEN }}
          registry: ${{ secrets.CODARREPO_URL }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
